### ISSUE TITLE
search result template

### ISSUE THREAD

**Issue by shrimp2t** [shrimp2t/nella-wp#12]
only display title and excerpt.
If no results then do something

---
Chỉ hiển thị title và exceprt
Nếu ko có kết quả thì là cái j đó thể thông báo

**Comment by thanhtd91** [comment]
Do you talk about post type post?

**Comment by shrimp2t** [comment]
Please check this search result page: http://dev02.ovicsoft.com/thang/nella/?s=sa
- Default search of blog posts
- Search for products.
PLEASE NOTE Only display title and excerpt
do not display post date
