### ISSUE TITLE
Improve the top left menu

### ISSUE THREAD

**Issue by shrimp2t** [shrimp2t/nella-wp#15]
"Welcome visitor you can login or create an account"

I can see the link when hover  on the "login" text but not for "create an account" so:
- can you make the links  easy to see ?
- can you add the link that take user to create account page ?

---

"Welcome visitor you can login or create an account"
Tôi nhìn thấy login link nhưng ko thấy create account link khi tôi rê chuột vào chữ "create an account" vậy:
- Hãy làm cho cái link dễ nhìn hơn.
-  Hãy thêm link vào cái create an account

**Comment by shrimp2t** [comment]
When i logged in the top left me must display something like this " Welcome UserDisplayName"
"UserDisplayName" link to profile page.

**Comment by thanhtd91** [comment]
Em fix cái này rồi anh vào xem được chưa anh

**Comment by shrimp2t** [comment]
cái này tạm ổn rồi.
