### ISSUE TITLE
Search form

### ISSUE THREAD

**Issue by shrimp2t** [shrimp2t/nella-wp#2]
Pleas fix: 
- Check and improve margin, padding, css (see screenshot).
http://d.pr/i/12AaD
- Dropdown must have hierarchical, check https://codex.wordpress.org/Function_Reference/wp_dropdown_categories
- Search form working incorrect.

**Comment by shrimp2t** [comment]
It's look like before fixed

**Comment by thanhtd91** [comment]
I have just fixed form search. You can review it
