### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by shrimp2t** [shrimp2t/nella-wp#3]
Install Monster widget https://wordpress.org/plugins/monster-widget/ and check with all widget sidebar.

Apply (add/edit) style for all elements in that widget sidebars

**Comment by shrimp2t** [comment]
Please apply CSS for Wiget Monster element because  it container all default WP widgets

**Comment by thanhtd91** [comment]
Can you check on site http://dev02.ovicsoft.com/thang/nella/ ? . We always upgrade lastest version on it.
